[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2018"

[[bin]]
name = "d1"
path = "src/d1/bin/main.rs"

[[bin]]
name = "d2"
path = "src/d2/bin/main.rs"

[dependencies]
